---
# defaults file for galaxyprojectdotorg.nginx

# Where should the role find ssl certificates to copy to the remote host
# (relative from where ansible-playbook is called if not
# absolute).
nginx_ssl_src_dir: files/ssl

# "flavor" of nginx to install
nginx_flavor: full

# where to install nginx configs
nginx_conf_dir: /etc/nginx

# whether nginx will run from supervisor
nginx_supervisor: false
nginx_supervisor_service_name: nginx

# enable ipv6 for the default vhost?
nginx_enable_default_ipv6: true

# additional nginx config files to install
nginx_configs: [ ]
