---
galaxy_info:
  author: The Galaxy Project
  description: Install and manage an nginx server.
  company: The Galaxy Project
  license: AFL v3.0
  min_ansible_version: 1.8
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - lenny
    - squeeze
    - wheezy
    - jessie
  - name: EL
    versions:
    - 6
    - 7
  - name: SmartOS
    versions:
    - all
    - any
  categories:
    - web
dependencies: []
